# Project information
site_name: OpenPLZ API
site_description: 'Dokumentation des OpenPLZ API Projekts'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://www.openplzapi.org/'

# Copyright
copyright: 
  '&copy; 2024 STÜBER SYSTEMS GmbH : <a href="https://legal.stueber.de/imprint.php">Impressum</a> : <a href="https://legal.stueber.de/privacy.php">Datenschutz</a>'

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/openpotato/openplzapi.website'

# Theming
theme:
  name: material
  language: de
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/brightness-7
        name: In den Dunkelmodus wechseln
    - scheme: slate
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/brightness-4
        name: In den Hellmodus wechseln
  font: false
  favicon: 'assets/logos/favicon.ico'
  logo: 'assets/logos/logo.svg'
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html

# Social media & multi language
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@openpotato
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openpotatis
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      lang: de

# Customization
extra_css:
  - assets/css/custom.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Navigation
nav:
  - Einführung: index.md
  - Referenz:
    - Deutschland: germany.md
    - Liechtenstein: liechtenstein.md
    - Schweiz: switzerland.md
    - Österreich: austria.md
    - Paging: paging.md
    - URL-Koderierung: url-encoding.md
    - Reguläre Ausdrücke: regex.md
    - Volltextsuche: fulltextsearch.md
    - Fehlermeldungen: errors.md
  - Änderungslog:
    - Daten: change-log-data.md
    - Web-Service: change-log-webservice.md
  - Datenquellen: sources.md
  - Client-Bibliotheken: libraries.md
  - Community: community.md
  - FAQ: faq.md
  - API: api.md
